app/routes.py
from flask import redirect,render_template,url_for,Blueprint,request,flash, make_response, send_from_directory
from flask import session, g
from flask_login import LoginManager,current_user,login_user,logout_user,login_required
from .database import *
from werkzeug.security import generate_password_hash,check_password_hash
from . import db
from functools import wraps
import fitz  # PyMuPDF
import datetime
from sqlalchemy import or_
from flask import request

# Open the PDF file





route = Blueprint('route', __name__)

def role_required(role):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if current_user is None or current_user.role != role:
                return render_template('login.html')
            return f(*args, **kwargs)
        return decorated_function
    return decorator

@route.route('/')
def home():
    exist_libra=User.query.filter_by(username="ds@harsh").first()
    if not exist_libra:
        librarian = User(username="ds@harsh", role="librarian", password_hash=generate_password_hash("password",method='scrypt'))
        db.session.add(librarian)
        db.session.commit()
    return render_template('home.html')

@route.route('/login',methods=['GET','POST'])
def login():
    if request.method=='POST':
        input_username = request.form.get('username')
        input_password = request.form.get('password')
        user = User.query.filter(input_username==User.username).first()
        if user:
            if check_password_hash(user.password_hash, input_password):
                flash("login sucessfully",category='success')
                login_user(user,remember=False)
                id = user.id
                return redirect(f'/user_dashboard/{id}')
            else:
                flash("wrong credentials",category="danger")
                return redirect('/')
        else:
            flash("User not registered try to register from signup page",category='error')
            return redirect('/signup')
    return render_template('login.html',user=current_user)

@route.route('/signup',methods=['GET','POST'])
def signup():
    if request.method=='POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter(username == User.username).first()
        if user:
            flash("Username is already taken try with different name",category='error')
        elif len(password) < 5:
            flash("Password should be of minimum 5 characters", category="error")
        else:
            user = User(username=username, role="user", password_hash=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            flash("User created successfully",category='success')
            return redirect('/login')
    return render_template('signup.html',user=current_user)

@route.route('/update/section/<int:id>',methods=['POST'])
def update_section(id):
    if request.method=="POST":
        title = request.form.get('title')
        section = Section.query.filter_by(id=id).first()
        if section:
            section_by_name = Section.query.filter_by(name=title).first()
            if section_by_name and section_by_name.id != section.id:
                flash("Section already exists",category='error')
                sections = Section.query.all()
                return render_template('librarian_dashboard.html',sections=sections)
            section.name = request.form.get('title')
            section.date = datetime.datetime.strptime(request.form.get('date'), '%Y-%m-%d').date()
            section.description = request.form.get('description')
            db.session.commit()
            flash("Section updated successfully",category='success')
            sections = Section.query.all()
            return render_template('librarian_dashboard.html',sections=sections)
        flash("Section not found",category='error')
        sections = Section.query.all()
        return render_template('librarian_dashboard.html',sections=sections)
@route.route('/update/book/<int:id>',methods=['POST'])
def update_book(id):
    if request.method=="POST":
        title = request.form.get('title')
        book = Book.query.filter_by(id=id).first()
        if book:
            book_by_name = Book.query.filter_by(title=title).first()
            if book_by_name and book_by_name.id != book.id:
                flash("Book already exists",category='error')
                books = Book.query.all()
                sections = Section.query.all()
                return render_template('books.html',books=books, sections=sections)
            book.title = request.form.get('title')
            book.author = request.form.get('author')
            book.price = request.form.get('price')
            book.content = request.files['content'].read()
            book.section_id = request.form.get('section_id')
            book.date = datetime.datetime.strptime(request.form.get('date'), '%Y-%m-%d').date()
            book.description = request.form.get('description')
            db.session.commit()
            flash("Book updated successfully",category='success')
            books = Book.query.all()
            sections = Section.query.all()
            return render_template('books.html',books=books, sections=sections)
        flash("Book not found",category='error')
        books = Book.query.all()
        sections = Section.query.all()
        return render_template('books.html',books=books, sections=sections)    
@route.route('/delete/section/<int:id>')
def delete_section(id):
        section = Section.query.filter_by(id=id).first()
        if section:
            db.session.delete(section)
            db.session.commit()
            flash("Section deleted successfully",category='success')
            sections = Section.query.all()
            return render_template('librarian_dashboard.html',sections=sections)
        flash("Section not found",category='error')
        sections = Section.query.all()
        return render_template('librarian_dashboard.html',sections=sections)
@route.route('/delete/book/<int:id>')
def delete_book(id):
    book = Book.query.filter_by(id=id).first()
    if book:
        db.session.delete(book)
        db.session.commit()
        flash("Book deleted successfully",category='success')
        books = Book.query.all()
        sections = Section.query.all()
        return render_template('books.html',books=books, sections=sections)
    flash("Book not found",category='error')
    books = Book.query.all()
    sections = Section.query.all()
    return render_template('books.html',books=books, sections=sections)
@route.route('/reuested/book/<int:id>')
def reuested_book(id):
    book = Book.query.filter_by(id=id).first()
    if book:
        register = Register(username=current_user.username, book_name=book.title, request_status='pending', user_id=current_user.id, book_id=book.id)
        db.session.add(register)
        db.session.commit()
        flash("Book requested successfully",category='success')
        return redirect(url_for('route.add_books'))
    flash("Book not found",category='error')
    return redirect(url_for('route.add_books'))
@route.route('/reject/book/<int:id>')
def reject_book(id):
    register = Register.query.filter_by(id=id).first()
    if register:
        register.request_status = 'rejected'
        db.session.commit()
        flash("Book rejected successfully",category='success')
        return redirect(url_for('route.add_books'))
    flash("Request not found",category='error')
    return redirect(url_for('route.add_books'))

@route.route('/revoke/book/<int:id>')
def revoke_book(id):
    register = Register.query.filter_by(id=id).first()
    if register:
        register.request_status = 'revoked'
        db.session.commit()
        flash("Book revoked successfully",category='success')
        return redirect(url_for('route.add_books'))
    flash("Request not found",category='error')
    return redirect(url_for('route.add_books'))
@route.route('/grant/book/<int:id>')
def grant_book(id):
    register = Register.query.filter_by(id=id).first()
    if register:
        register.request_status = 'granted'
        db.session.commit()
        flash("Book granted successfully",category='success')
        return redirect(url_for('route.add_books'))
    flash("Request not found",category='error')
    return redirect(url_for('route.add_books'))

@route.route('/books',methods=['GET','POST'])
def add_books():
    if request.method=='POST':
        title = request.form.get('title')
        author = request.form.get('author')
        price = request.form.get('price')
        content = request.files['content'].read()
        description = request.form.get('description')
        section_id = request.form.get('section_id')
        if Book.query.filter_by(title=title).first():
            flash("Book already exists",category='error')
            books = Book.query.all()
            sections = Section.query.all()
            return render_template('books.html',books=books, sections=sections)
        date = request.form.get('date')
        book = Book(title=title, author=author, price=price, content=content, section_id=section_id, description=description, date=datetime.datetime.strptime(date, '%Y-%m-%d').date())
        db.session.add(book)
        db.session.commit()
        flash("Book added successfully",category='success')
        books = Book.query.all()
        sections = Section.query.all()
        return render_template('books.html',books=books, sections=sections)
    param = request.args.get('param')
    remove = request.args.get('remove')
    search_word=request.args.get('search')
    books=None
    if search_word:
        books = Book.query.filter(or_(
            Book.title.ilike(f'%{search_word}%'),
            Book.author.ilike(f'%{search_word}%'),
            Book.description.ilike(f'%{search_word}%'),

app/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library Management System</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            color: #333;
        }

        header {
            background-color: #3498db;
            padding: 1em;
            text-align: center;
            color: white;
            font-size: 2em;
        }

        .main-content {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .welcome-section {
            background-color: #3498db;
            color: white;
            padding: 50px;
            border-radius: 10px;
            text-align: center;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .welcome-section h1 {
            font-size: 3em;
            margin-bottom: 20px;
        }

        .welcome-section p {
            font-size: 1.2em;
            margin-bottom: 40px;
        }

        .button-container {
            display: flex;
            gap: 20px;
        }

        .button {
            background-color: #3498db;
            color: white;
            border: none;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 1.5em;
            cursor: pointer;
            border-radius: 8px;
            transition: background-color 0.3s ease-in-out;
        }

        .button:hover {
            background-color: #2980b9;
        }
    </style>
</head>

<body>
    <header>
        Library Management System
    </header>
    <div class="main-content">
        <div class="welcome-section">
            <h1>Welcome to Our Library</h1>
            <p>Discover a world of knowledge and adventure.</p>
            <div class="button-container">
                <a href="{{ url_for('route.login') }}" class="button">User Login</a>
                <a href="{{ url_for('route.signup') }}" class="button">User Signup</a>
                <a href="{{ url_for('route.librarian_login') }}" class="button">Librarian Login</a>
            </div>
        </div>
    </div>
</body>

</html>

app/templates/librarian_dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome to central library</title>
  <style>
    body {
      padding-top: 16px;/
    }
  </style>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Librarian's Dashboard</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('route.librarian_dashboard')}}">dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('route.stats')}}">stats</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('route.add_books')}}">books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('route.requests')}}">requests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('route.logout')}}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-5">
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category =='error' %}
    <div class="alert alert-danger alter-dismissible fade show row justify-content-evenly w-25" role="alert">
      <div class="col-10">
        {{ message }}
      </div>
      <div class="col-2">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissible fade show row justify-content-evenly w-25" role="alert">
      <div class="col-8">
        {{ message }}
      </div>
      <div class="col-2">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}
    <header class="mb-4">
      <div class="container text-center">
        <div class="row">
          {% if search_by %}
          <div class="col">
            <h3>Search results for <p class="text-info">{{ search_by }}</p>
            </h3>
          </div>
          {% else %}
          <div class="col">
            <h3>All Sections to view</h3>
          </div>
          {% endif %}
          <div class="col-6">
            <form method="GET">
              <div class="input-group">
                <input type="text" class="form-control" name="search" placeholder="Search term" aria-label="Search term"
                  aria-describedby="button-addon">
                <button class="btn btn-light" type="submit" id="button-addon">Search</button>
              </div>
            </form>
          </div>
          <div class="col">
            <div class="btn-group dropend">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                aria-expanded="false">
                filter by
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{url_for('route.librarian_dashboard',  param=" today")}}">today</a>
                </li>
                <li><a class="dropdown-item" href="{{url_for('route.librarian_dashboard',  param=" last week")}}">last
                    week</a></li>
                <li><a class="dropdown-item" href="{{url_for('route.librarian_dashboard',  param=" last month")}}">last
                    month</a></li>
                <li><a class="dropdown-item" href="{{url_for('route.librarian_dashboard',  param=" last year")}}">last
                    year</a></li>
              </ul>
            </div>
            <a href="{{url_for('route.librarian_dashboard')}}" class="btn btn-light">clear all</a>
          </div>
        </div>
      </div>
    </header>
    <header class="mb-3">
      {% if g.params %}
      {% for param in g.params %}
      <span class="badge rounded-pill text-bg-light">{{param}} <a
          href="{{url_for('route.librarian_dashboard', remove=param)}}" style="cursor: pointer;">&Cross;</a></span>
      {% endfor %}
      {% endif %}
    </header>
    <div class="row gap-3">
      {% if sections|length > 0 %}
      {% for section in sections %}
      <div class="col-md-3">
        <div class="card border-primary shadow-lg rounded-5">
          <div class="card-body">
            <div class="card-body">
              <p class="card-title"><b>Section:</b> {{section.name}}</p>
              <p class="card-title"><b>Date:</b> {{ section.date.strftime('%Y-%m-%d') }}</p>
              <p class="card-title"><b>description:</b> {{ section.description }}</p>
              <div class="d-flex justify-content-around">
                <a href="{{url_for('route.add_books')}}" class="btn btn-primary">Add Book</a>
                <a href="{{url_for('route.add_books')}}" class="btn btn-info" data-bs-toggle="modal"
                  data-bs-target="{{'#'+section.name}}">Edit</a>
                <div class="modal fade" id="{{section.name}}" data-bs-backdrop="static" data-bs-keyboard="false"
                  tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content border-primary shadow-lg rounded-5">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">updating section</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <form class="page" action="{{url_for('route.update_section', id=section.id)}}" method="POST">
                          <div class="form-group">
                            <input type="hidden" name="id" value="{{section.id}}">
                            <label for="title">Title</label>
                            <input type="text" id="title" name="title" class="form-control"
                              placeholder="{{section.name}}" maxlength="20" required />
                            <br />
                            <label for="date">Date</label>
                            <input type="date" id="date" name="date" class="form-control"
                              value="{{section.date.strftime('%Y-%m-%d')}}" required />
                            <br />
                            <label for="description">Description:</label>
                            <textarea type="text" id="description" name="description" class="form-control"
                              maxlength="50" required>{{section.description}}</textarea>
                          </div>
                      </div>
                      <div class="modal-footer d-flex justify-content-around">
                        <button type="submit" class="btn btn-success">update</button>
                        <a href="{{url_for('route.delete_section', id=section.id)}}" class="btn btn-danger"
                          onclick="confirm('Are you sure?')">delete</a>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <p class="text-warning">No sections found</p>
      {% endif %}
      <div class="col-md-2 d-flex align-items-center">
        <!-- Button trigger modal -->
        <a href="" class="myhover" data-bs-toggle="modal" data-bs-target="#staticBackdrop2">
          <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50">
            <circle cx="25" cy="25" r="20" stroke="blue" stroke-width="2" fill="white" />
            <line x1="25" y1="15" x2="25" y2="35" style="stroke:blue;stroke-width:2" />
            <line x1="15" y1="25" x2="35" y2="25" style="stroke:blue;stroke-width:2" />
          </svg>
        </a>
      </div>
    </div>
  </div>
  <div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content border-primary shadow-lg rounded-5">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Add New Section</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="login" class="page" method="POST">
            <div class="form-group">
              <label for="title">Title</label>
              <input type="text" id="title" name="title" class="form-control" maxlength="20" required />
              <br />
              <label for="date">Date</label>
              <input type="date" id="date" name="date" class="form-control" required />
              <br />
              <label for="description">Description:</label>
              <textarea id="description" name="description" class="form-control" maxlength="50" required></textarea>
            </div>
        </div>
        <div class="modal-footer d-flex justify-content-around">
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">cancel</button>
          <button type="submit" class="btn btn-success">add</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

app/templates/librarian_request.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome to central library</title>
  <style>
    body {
        padding-top: 16px; /
    }
  </style>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Librarian's Dashboard</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('route.librarian_dashboard')}}">dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('route.stats')}}">stats</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('route.add_books')}}">books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('route.requests')}}">requests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('route.logout')}}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-5">
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category =='error' %}
    <div class="alert alert-danger alter-dismissible fade show row justify-content-evenly w-25" role="alert">
      <div class="col-10">
        {{ message }}
      </div>
      <div class="col-2">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissible fade show row justify-content-evenly w-25" role="alert">
      <div class="col-8">
        {{ message }}
      </div>
      <div class="col-2">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}    
    <header class="mb-4">
      <div class="container text-center">
        <div class="row">
          {% if search_by %}
          <div class="col">
            <h3>Search results for <p class="text-info">{{ search_by }}</p></h3>
          </div>
          {% else %}
          <div class="col">
            <h3>All requests to view</h3>
          </div>
          {% endif %}
          <div class="col-6">
            <form method="GET">
              <div class="input-group">
                  <input type="text" class="form-control" name="search" placeholder="Search term"
                      aria-label="Search term" aria-describedby="button-addon">
                  <button class="btn btn-light" type="submit" id="button-addon">Search</button>
              </div>
            </form>
          </div>
          <div class="col">
            <div class="btn-group dropend">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                filter by
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{url_for('route.librarian_dashboard',  param="today")}}">today</a></li>
                <li><a class="dropdown-item" href="{{url_for('route.librarian_dashboard',  param="last week")}}">last week</a></li>
                <li><a class="dropdown-item" href="{{url_for('route.librarian_dashboard',  param="last month")}}">last month</a></li>
                <li><a class="dropdown-item" href="{{url_for('route.librarian_dashboard',  param="last year")}}">last year</a></li>
              </ul>
            </div>
            <a href="{{url_for('route.librarian_dashboard')}}" class="btn btn-light">clear all</a>
          </div>
        </div>
      </div>
    </header>
    <header class="mb-3">
      {% if g.params %}
        {% for param in g.params %}
          <span class="badge rounded-pill text-bg-light">{{param}} <a href="{{url_for('route.librarian_dashboard', remove=param)}}" style="cursor: pointer;">&Cross;</a></span>
        {% endfor %}
      {% endif %}
    </header>
    {% if requesteds|length > 0 %}
    {% for requested in requesteds %}
    <div class="d-flex"> 
      <div class="shadow p-3 bg-body-tertiary rounded p-2 flex-grow-1">{{requested.book_name}} <a href="" data-bs-toggle="modal" data-bs-target="{{'#staticBackdrop'+requested.id|string}}">{{requested.username}}</a></div>
      {% if requested.status == 'pending' %}
      <a href="{{url_for('route.reject_book', id = requested.id)}}" class="btn btn-danger me-2 p-2 ">reject</a>
      <a href="{{url_for('route.grant_book', id = requested.id)}}" class="btn btn-success me-2 p-2 ">grant</a>
      {% else %}
      <a href="{{url_for('route.reject_book', id = requested.id)}}" class="btn btn-danger p-2 ">revoke</a>
      <button type="button" class="btn btn-success me-2 p-2 " disabled>{{requested.request_status}}</button>
      {% endif %}
    </div>
    <div class="modal fade" id="{{'staticBackdrop'+requested.id|string}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-primary shadow-lg rounded-5">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="staticBackdropLabel">User info</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form id="login" class="page" method="POST">
              <div class="form-group">
                  <label for="title">User Name: {{requested.username}}</label>
                  <br />
                  <label for="date">Day requested: {{requested.requested_date}} </label>
                  <br />
                  <label for="image">Book title: {{requested.book_name}}</label>
              </div>
            </form>
          </div>
          <div class="modal-footer d-flex justify-content-around">
            <button type="button" class="btn btn-danger" disabled>#book_issued: {{requested.no_book_issued}}</button>
            <button type="button" class="btn btn-success" disabled>#book_requested: {{requested.no_book_requested}}</button>
            <button type="button" class="btn btn-warning" disabled>Trust Score: 2/5</button>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <p class="text-warning">No requests found</p>
    {% endif %}
</div>
</body>

</html>

app/templates/login.html
{% extends "base.html" %}
{% block title %} User Login Page {% endblock %}
{% block content %}
<div class="d-flex justify-content-center align-items-center vh-100">
    <div class="card w-25 border-primary shadow-lg">
        <div class="card-body">
            <form id="login" class="page" method="POST">
                <h3 class="input">User Login</h3>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" class="form-control" placeholder="Enter Username" size="10" />
                    <br />
                    <label for="password">Password</label>
                    <input type="password" id="password_id" name="password" class="form-control" placeholder="Enter Password" size="15" />
                    <br />
                    <div class="d-flex justify-content-around">
                        <button class="btn btn-info bg-opacity-10" type="submit">Login</button>
                        <a href="{{ url_for('route.signup') }}" class="btn btn-warning bg-opacity-10" >Register</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}